### PR TITLE
Port for qnx

### PR DESCRIPTION
**Pull request by pkleymonov-qnx**
It has two commits:
- essential changes in main source tree
- qnx build and tests infrastructure under ./qnx/

### CODE REVIEW

**Comment by gstrauss** [comment]
Thank you for this thorough contribution!

I would be happy to accept the small changes to `src/fdevent.h` `src/server.c` and `tests/mod-fastcgi.t`

My initial thought is that the rest of the commit `qnx/*` might do better as a separate repository since I do not maintain a QNX development environment.  I would be happy to include some comments in `INSTALL` for qnx to obtain the `qnx/` tree, e.g. as a git submodule.  How will this `qnx/` tree be maintained?  e.g. the list of modules in `qnx/shiplist/shiplist-sdp-lighttpd-internal.xml`.  (`mod_vhostdb.so` is useless without another mod_vhostdb_???.so provider).  Does the `qnx/` tree need to be at the top level of the source tree?  Could it be under a more generically useful `arch/`, e.g. `arch/qnx`?  Is there a more widely used convention for OS-specific trees?

**Comment by gstrauss** [comment]
@pkleymonov-qnx could the `qnx/` directory move out of the root and under a directory named `os/` ?

**Comment by pkleymonov-qnx** [comment]
Thank you @gstrauss for the review.
Please see my answers below.

> I would be happy to accept the small changes to `src/fdevent.h` `src/server.c` and `tests/mod-fastcgi.t`

Should I create separate pull request just for these three changes?

> How will this `qnx/` tree be maintained? e.g. the list of modules in `qnx/shiplist/shiplist-sdp-lighttpd-internal.xml`. 

Soon we will have separated fork with 'qnx/' tree under this link:
 https://github.com/qnx/lighttpd1.4 (not created yet)
From time to time this fork will be updated to the never version.
We also run all tests (unittest as well as perl test scripts) on x86_64 and aarch64le architecrure on QNX7.1/8.0

> Does the `qnx/` tree need to be at the top level of the source tree? 
> Could it be under a more generically useful `arch/`, e.g. `arch/qnx`?

It is possible to move it under 'arch/qnx' for that we need to update variable NESTED_LEVEL within file: qnx/build/build-hooks

> Is there a more widely used convention for OS-specific trees?

For example here: https://github.com/Perl/perl5
you can see that they are using 'qnx/' tree.

**Comment by gstrauss** [comment]
> > I would be happy to accept the small changes to `src/fdevent.h` `src/server.c` and `tests/mod-fastcgi.t`
> 
> Should I create a separate pull request just for these three changes?

Not necessary.  You helpfully isolated this in a separate commit.  I cherry-picked the first commit.  Thanks!

> Soon we will have separated fork with 'qnx/' tree under this link:
> https://github.com/qnx/lighttpd1.4 (not created yet)
> From time to time, this fork will be updated to the newer version.
> We also run all tests (unittest as well as perl test scripts) on x86_64 and aarch64le architecture on QNX7.1/8.0

Sounds good.  I'll add a link in `INSTALL`.
I think that you are in a much better position than I am to maintain the `qnx/` tree.

While I have a warm spot in my heart for Perl, the kitchen sink of files and directories at the top of the Perl source tree is not a something I would like to emulate. :smiley: 

FYI: Apache httpd has `os/` and OS-specific subdirs and code underneath.

I would pull your commit into `os/qnx/` if that is amenable to you, and you update the NESTED_LEVEL.

---

If you have feedback or ideas on how to improve lighttpd or address limitations running lighttpd on QNX, please open an issue in github here, or the lighttpd developer forum: https://redmine.lighttpd.net/projects/lighttpd/boards/3  Thanks!

**Comment by pkleymonov-qnx** [comment]
> 
> FYI: Apache httpd has `os/` and OS-specific subdirs and code underneath.
> 
> I would pull your commit into `os/qnx/` if that is amenable to you, and you update the NESTED_LEVEL.
> 

No issue. Just let me know and i will adjust it.
As well as execute all tests on qnx7.1/8.0 x86_64/aarch64le

**Comment by gstrauss** [comment]
> > FYI: Apache httpd has `os/` and OS-specific subdirs and code underneath.
> > I would pull your commit into `os/qnx/` if that is amenable to you, and you update the NESTED_LEVEL.
> 
> No issue. Just let me know and i will adjust it. As well as execute all tests on qnx7.1/8.0 x86_64/aarch64le

Sounds good to me, but I do not claim wide expertise in this area, yet prefer a little bit of organization where it makes sense.  Unless you have an objection -- in which case please voice it -- please go ahead and adjust the path to `qnx/` to be `os/qnx/` including NESTED_LEVEL, and I will accept the patch into lighttpd.  Hopefully, you'll make occasional future pull requests when the os/qnx/ tree needs to be updated. :)

**Comment by gstrauss** [comment]
@pkleymonov-qnx please hold on that change for a moment.  I am chatting with stbuehler, another lighttpd developer, who does not think the qnx/ should be part of the lighttpd distribution.  The better choice might be https://github.com/qnx/lighttpd1.4, maybe with qnx/ in a separate repository as a git submodule.

**Comment by pkleymonov-qnx** [comment]
@gstrauss Thank you very much for reasonable remarks.

Please see my comments below.

> I see that https://github.com/qnx/lighttpd1.4 has been created, but it looks like a standalone repository instead of a fork of this repository. It would be better if that repository were created on github as a fork of this repository.
> 

This is a good idea.
Never the less our approach based on idea that we have to support also opensource projects which are originated on different git servers. For instrance gitlab.com, bitbucket.org etc.

For the first glance it looks better to copy all projects with our specific changes.
Although it may be changed in future.


> I recommend that the code with the qnx/ directory be a separate branch in your repository, although that is not a hard requirement. I recommend that you periodically _rebase_ the qnx branch against the upstream lighttpd git master branch in this repository.

Our copy will be in sync with  https://github.com/lighttpd/lighttpd1.4 and in additional will have full tested release version on specific branch. For instance: release tag lighttpd-1.4.73 will have correspondent branch qnx-sdp-lighttpd-1.4.73

As soon as we will make a full tests for newer release, we will create another branch accordingly.

As I told, this may be changed in future, and we will follow general github approach with fork method for github.com only projects. 

And for other projects we will have separate collection on other git servers.

**Comment by gstrauss** [comment]
Are you comfortable where things stand?  May I close this PR?  The small changes you submitted for lighttpd code to be compatible with QNX have been committed, and it makes sense to me for QNX to manage the QNX build scripts, e.g. under QNX controlled repo https://github.com/qnx/lighttpd1.4.

If you have further suggestions for how to improve lighttpd (besides the qnx/ subdirectory), you are welcome to open a new issue or submit a new PR.

**Comment by pkleymonov-qnx** [comment]
@gstrauss No issue. Please close this PR. Thank you very much.

**Comment by gstrauss** [comment]
Thank you, @pkleymonov-qnx for your contribution!

**Pull request closed without merging**
