### PR TITLE
[mod_openssl] compile fix for CentOS-7

### PR DESCRIPTION
**Pull request by gmd20**
X509_get0_notBefore is not defined in openssl-devel-1.0.2k header files.

### CODE REVIEW

**Comment by gstrauss** [comment]
Thanks for the patch.  I'll review it for inclusion in a future lighttpd release.

Just in case you or others did not know, all versions of openssl < 1.1.1 are end-of-life and no longer receiving security patches from openssl.org: https://endoflife.software/applications/security-libraries/openssl

**Comment by gstrauss** [comment]
I think I prefer this, since `X509_get_notBefore` and `X509_get_notAfter` were deprecated in OpenSSL 1.1.0
```
--- a/src/mod_openssl.c
+++ b/src/mod_openssl.c
@@ -1275,12 +1275,20 @@ network_ssl_servername_callback (SSL *ssl, int *al, void *srv)
 #endif
 
 
-#if defined(BORINGSSL_API_VERSION) \
+#if OPENSSL_VERSION_NUMBER < 0x10101000L \
+ || defined(BORINGSSL_API_VERSION) \
  || defined(LIBRESSL_VERSION_NUMBER)
 static unix_time64_t
 mod_openssl_asn1_time_to_posix (const ASN1_TIME *asn1time);
 #endif
 
+#if OPENSSL_VERSION_NUMBER < 0x10100000L \
+ && !defined(BORINGSSL_API_VERSION) \
+ && !defined(LIBRESSL_VERSION_NUMBER)
+#define X509_get0_notBefore X509_get_notBefore
+#define X509_get0_notAfter  X509_get_notAfter
+#endif
+
 static int
 mod_openssl_cert_is_active (const X509 *crt)
 {
```

**Comment by gstrauss** [comment]
> X509_get0_notBefore is not defined in openssl-devel-1.0.2k header files.

Is CentOS 7 using at least openssl 1.0.2u?  If not, why not?

**Comment by gmd20** [comment]
> > X509_get0_notBefore is not defined in openssl-devel-1.0.2k header files.
> 
> Is CentOS 7 using at least openssl 1.0.2u? If not, why not?

openssl-1.0.2k is the lastest official version on CentOS-7,  I think CentOS-7(or Redhat)  will privide security fixes till the end of life of CentOS-7.   BTW, your patches is acceptable.

**Pull request closed without merging**
