### PR TITLE
Personal/mchalain/cleanup openssl

### PR DESCRIPTION
**Pull request by mchalain**
Hello Happy World,

I worked on the port of mbedtls in place of openssl.
My first step was to cleanup the specific code of OpenSSL to move it in only one file and to have an API to use with mbedtls.

Then I join a collection of patches that move the code slowly and minimize the modifications into the sequences.
Some patches are more important than the others:

- 0009-openssl-store-specific_config-into-srv_socket.patch : this patch is not dangerous but the modification may be use to simplify some other part of the code.

- 0011-openssl-manage-tlsext_server_name-into-connection.patch : the tlsext_server_name is allocated only for HTTPS connection, but I didn't find configuration to allow to use it.

- 0012-openssl-move-SSL-configuration-into-new-function.patch : the connection configuration copied all variables. This patch copy the SSL configuration only for a HTTPS connection.

- 0014-opensll-anonymize-SLL-variables-into-base.h.patch : the certificates variables were copied into each connection, but they were the same for each server_socket. Then this patch copy a pointer to a structure that contains the variables.

Before to continue I would like to discuss about this patches, to be sure that I didn't take the wrong way.

My next step will be to create a mod_openssl but this may introduce some bugs and regressions. Then the cleanup has to be ready before to begin this step.

Best regards, merry Christmas and see you next year,
Marc.

### CODE REVIEW

**Comment by gstrauss** [comment]
Thanks for the effort!

I had hoped you would see my update to https://redmine.lighttpd.net/boards/4/topics/6988 where I ported mod_openssl from a (diverged) development branch of mine and pushed so that you could see its state.  From a quick glance, it looks like many of your patches have been addressed in the dev branch posted at the link above.

Even if some of the work has been duplicated, I am sure that your changes will be useful to inform me how you were approaching the module and what you need to further developing mbedtls module for lighttpd.  I am interested in your feedback on the dev branch posted in https://redmine.lighttpd.net/boards/4/topics/6988 and what further changes might be needed.  Cheers.

x-ref:
https://redmine.lighttpd.net/boards/4/topics/6988
https://redmine.lighttpd.net/boards/3/topics/7029

**Comment by mchalain** [comment]
Hello,
I'll read your dev/branch and answer quickly.
Thank you

2016-12-31 5:20 GMT+01:00 Glenn Strauss <notifications@github.com>:

**Comment by mchalain** [comment]
Hello Glenn,

I read each of your commits and I wrote some remarks and questions. They
are not requests or criticisms, but a beginning for more discussions.
I'm interested to help you to develop some features. And I will begin with
mbedTLS.

*acc912f70913*

connection_read_cq: why "force_assert(max_bytes == MAX_READ_LIMIT)" ? the
max_bytes parameter is useless.
connection_write_cq: why connection_read_cq inside connections-glue.c and
connection_write_cq inside connections.c ? What's the meaning of "-glue" ?

*623f3fcbb0c5*

array_insert_unique: free the buffer of tlsext_server_name without check
the value.
tlsext_server_name: free here but not allocated into the mod.

*40d3ed3c24e5*

config_insert: link ssl support to OpenSSL, but ssl may be supported by
others libraries.

*262634ef6f7bd9845de0d*

config_insert: unused-slot-moved-to-mod-openssl is a good idea, but for an
embeded server, it's taken memroy for nothing.
mod_openssl_handle_con_accept: retrieves the specific_config of srv_socket
with sidx, but the connection contains the specific_config. What is the
difference ?
connection_init: use the macro's name "CLEAN" to initiliaze, is not a good
idea. I think that a renaming should be interesting.
network_server_init: what is the link between openssl and the modification
of the parameter of this function ? May another commit gives more
explanation ?
show_features: display SSL support for OpenSSL only.

*be66471cbcf5a71ad2fc*

connection_read_cq: I see that you are agree with my previous question. But
do you known the meaning of "-glue" in this case ?

Best regards,
Marc.


2017-01-02 13:48 GMT+01:00 Marc Chalain <marc.chalain@gmail.com>:

**Comment by gstrauss** [comment]
@mchalain:  I have tried to answer your questions below, and I hope the answers are useful to you.
On the other hand, I question the utility of your "code review" comments and remarks.  Maybe you should omit your "code review" comments until you are more familiar with the code base?

Overall, the patches aim to isolate the openssl code into a module, separate from the main server, to allow an alternate module to be written (e.g. mod_mbedtls) which provides similar functionality, also isolated from the main server.

> connection_read_cq: why "force_assert(max_bytes == MAX_READ_LIMIT)" ? the max_bytes parameter is useless.

Code was modified to isolate openssl code, and this was an assumption in the code that, for the moment, is being preserved in order to reduce the code diff.  This is noted in the comment directly next to the code:
`force_assert(max_bytes == MAX_READ_LIMIT); /*(code transform assumption; minimize diff)*/`
Why bother asking this question?

> connection_write_cq: why connection_read_cq inside connections-glue.c and connection_write_cq inside connections.c ?

Why ask this question?  connection_read_cq() was moved back to connections.c in 9481c102 after function pointers were introduced for these connection methods.

> What's the meaning of "-glue" ?

Good question.  This is due to physical dependencies of the code and their callers.  connections.c is built into the main server.  connections-glue.c contains routines which might be called from modules.  connections-glue.c is built into a shared library on platforms such as Mac OSX where shared libraries (e.g. lighttpd modules such as mod_openssl) can not call back into symbols in the main executable.

> array_insert_unique: free the buffer of tlsext_server_name without check the value. tlsext_server_name: free here but not allocated into the mod.

These are not questions.  The code (was) correct.  I think you may have been confusing con->tlsext_server_name with mod_openssl hctx->tlsext_server_name (specific to mod_openssl).  Besides con->tlsext_server_name and mod_openssl hctx->tlsext_server_name were both removed in a subsequent commit: 5f7d16a0.

> config_insert: link ssl support to OpenSSL, but ssl may be supported by others libraries.

That is an attempt to preserve an existing user-friendly error, and no other TLS implementation modules currently exists (yet) for lighttpd.  The error might be extended or simply removed in future versions since other ssl.* directives will be reported as unrecognized directives (though only as warnings).

> config_insert: unused-slot-moved-to-mod-openssl is a good idea, but for an embeded server, it's taken memroy for nothing.

This is really insignificant.  You're over-optimizing.  Besides, as with any optimization, please quantify the impact if you want the (perceived) issue to be taken seriously.  (Yes, this could be cleaned up in a separate commit, but would have made for a messier diff if it had been combined with the functional changes in the commit that substituted "unused-slot-moved-to-mod-openssl".)

> mod_openssl_handle_con_accept: retrieves the specific_config of srv_socket with sidx, but the connection contains the specific_config. What is the difference ?

Good question.  The **mod_openssl** config context in the **same** config context as $SERVER["socket"] is retrieved with sidx, and this mod_openssl config context contains the initialized (SSL_CTX *) associated with (server_socket *), instead of storing (void *) data members in the (server_socket *) for the benefit of a specific module (mod_openssl).  The server has the values of some directives stored in (specific_config), and each module (potentially) has its own (plugin_config) with the values of the module's directives.

> connection_init: use the macro's name "CLEAN" to initiliaze, is not a good idea. I think that a renaming should be interesting.

Out of scope.  While I don't like the CLEAN macro either, it matches current use in other modules.  You may choose to do this slightly differently in mod_mbedtls.  That's fine.

> network_server_init: what is the link between openssl and the modification of the parameter of this function ? May another commit gives more explanation ?

See above explanation of the use of sidx to match the config context of (server_socket *) with the module config context.  This is not something previously needed by any other modules.

> show_features: display SSL support for OpenSSL only.

As noted above, there are no other TLS modules currently available for lighttpd.  This command line output can be changed, but since it is merely informational, it is low priority.

> connection_read_cq: I see that you are agree with my previous question. But do you known the meaning of "-glue" in this case ?

Why are you saying this?  I could not have "agreed with" your prior comment since both commits occurred well before you had the opportunity to look at any of these commits.  What is the purpose of your statement?  Comments like this are a waste time.  You could have just gone and deleted this and your prior comment, and retained the question asking about the difference between connection.c and connection-glue.c instead of asking the same question twice.  Please try to be concise when asking questions.  This should be a list of questions with appropriate context, not a storybook conversation.

As you can see, I am more than willing to answer your questions.  At the same time, I hope you take my criticism and try to ask more focused questions.  Cheers.

**Comment by mchalain** [comment]
My code review allows to known the base code fastly. With it, I can send
questions.
I will read your answer, but first you can find here a very small patch for
your branch.
Thank you

2017-01-05 20:59 GMT+01:00 Glenn Strauss <notifications@github.com>:

**Comment by mchalain** [comment]
Ok I understand your criticism, and I'm sorry to importune you.
My point of view is that each commit has to build and run. Then I try to
understand each commit. I work like that for a long time, it's not easy to
change.

I understand the problem with "glue" now. I didn't see the library and
never think to the necessity , then I didn't understand, sorry. But with
the good option of the linker, it is possible to call the application
functions from any library on any platform ( with gcc the option is
-rdynamic).

As I told you it wasn't a review board, but I tried to understand some part
of code and know your point of view about others. Then my question about
"CLEAN" wasn't out of scope. I asked your point of view about it. My point
of view is that to use the word "CLEAN" every where, obfuscates the code,
and a future commit may be change this word every where.

idem for the unused-slot-moved-to-mod-openssl. I agree it is not a lot of
memory, But it's useless code, and may be removed in a future commit. If
you , now.agree to remove it, I can do it, but before to send an useless
patch, I prefer to ask you.

Best regards

2017-01-06 9:27 GMT+01:00 Marc Chalain <marc.chalain@gmail.com>:

**Comment by mchalain** [comment]
Sorry for the mistakes

2017-01-06 16:50 GMT+01:00 Marc Chalain <marc.chalain@gmail.com>:

**Comment by gstrauss** [comment]
> My point of view is that each commit has to build and run.

That is not an assumption you shared up front, and is not a universal truth.

> Then I try to understand each commit.

That's fine.  Still, code reviews of a multi-commit branch should omit earlier remarks that are obsoleted by later commits in the same multi-commit dev branch.

In general, I, too, prefer each commit to be buildable.  However, I sometimes make an exception for large changes where a couple incremental patches make the diffs easier to review.  Were I not working so quickly to integrate my changes into a new dev branch for you, I probably would have done code moves in one commit, resulting in a broken branch, and then the code modifications to have it build in a second commit, so that only code changes were visible in the second commit, and the large code move commit could be ignored during review.

Regarding the acceptance of patches:
* If you would like to contribute to lighttpd, please do so with functional, utilitarian patches instead of mere code aesthetics.
* If code formatting and spelling in an old and stable open source project bother you so greatly that you can not write functional code, then I suggest trying to isolate your contributions so that you do not have to touch such "icky" code.

With the changes that I have presented in my dev branch, you should have to touch very little, if any, code outside of (a copy of) mod_openssl.c in order to write mod_mbedtls.c.  Inside mod_mbedtls.c, you may follow (just about) any reasonable coding convention as long as it is self-consistent.

If you would like to submit a patch which properly adjusts all the array assignments in configfile.c in order to remove "unused-slot-moved-to-mod-openssl", I will (hesitantly) consider such a patch, but would prefer if we focused on mod_openssl and mod_mbedtls.  In general, I will occasionally accept such patches, but such cleanups make using the commit history more difficult and cumbersome, as one has to iterate over and over through 'git annotate' to step past each and every "cleanup" patch to find functional changes of importance.  Again, I would prefer to focus on mod_openssl and mod_mbedtls.

If you would like to work with me to "clean up" mod_openssl.c, I will accept patches for that, such as replacing the CLEAN() macro.  On the other hand, I am not currently interested in "cleanup" patches that touch hundreds or thousands of lines of code across the entire codebase, so please **do not** spend time doing that.

.

IMNSHO, one (of numerous) measures of a senior programmer is the ability to work with a codebase and make improvements to it **without** first having to rewrite or touch many, many lines of code across the entire codebase.  You seem not to grasp the value of a useful commit history to **other** senior programmers.

> My point of view is that to use the word "CLEAN" every where, obfuscates the code, and a future commit may be change this word every where.

While this is a possibility, it is also unlikely.  I feel that there are more important places to spend time on the lighttpd code base.  Additionally, mechanical changes to the code base are better done with a script, across the entire code base, and done sparingly (once in a long while), so as to disrupt the commit history as few times as possible.

> I will read your answer, but first you can find here a very small patch for your branch.

Sorry, I did not see any patch attached.  Where might I find it?  Thanks.

**Comment by gstrauss** [comment]
In an effort to keep this pull request a bit more focused, I am planning to close this pull request ("Personal/mchalain/cleanup openssl") some time later this week unless there are requirements in your patches that have not be addressed by the patch set in my dev branch.

Are there any specific parts of **your** patches submitted in this pull request which should be discussed further?  Thanks.

**Comment by gstrauss** [comment]
>> I will read your answer, but first you can find here a very small patch for your branch.

> Sorry, I did not see any patch attached. Where might I find it? Thanks.

no response.

> Are there any specific parts of **your** patches submitted in this pull request which should be discussed further? Thanks.

no response.

.

As I noted above:
> With the changes that I have presented in my dev branch, you should have to touch very little, if any, code outside of (a copy of) mod_openssl.c in order to write mod_mbedtls.c. Inside mod_mbedtls.c, you may follow (just about) any reasonable coding convention as long as it is self-consistent.

I hope you'll consider focusing on mod_mbedtls.c based off of the dev branch I provided which isolates openssl code into mod_openssl.c

If you have development questions, please ask in the lighttpd forums or on IRC freenode #lighttpd.
The lighttpd development forum is at: https://redmine.lighttpd.net/projects/lighttpd/boards/3

**Pull request closed without merging**
