### PR TITLE
[mod_cgi] consolidate CGI cleanup code

### PR DESCRIPTION
**Pull request by gstrauss**
(more consistent behavior)
    
reference:
  "Race leads to incorrect output in some circumstances"
  https://redmine.lighttpd.net/issues/2542

### CODE REVIEW

**Comment by stbuehler** [comment]
Thanks! Applied in dde7bea99a259ab760c1eadab01ea0ea6f5bdb6f.

**Comment by gstrauss** [comment]
@stbuehler, there is a whole lot more in this patch than just the last commit of the 4 commits in this branch.  Would you take another look?  Would you rather me squash them all together?

**Comment by stbuehler** [comment]
Sorry, I only listed the final commit (the first of these four was #30 anyway); the other two were applied in e5e66f791f43e64c3b3d82c05aad8f6e845dd29a and f2cbd0a3aaf3db34404de35919397a7e15dccaca) - with some minor changes by me.

**Comment by gstrauss** [comment]
oh, I see.  Thanks!

**Pull request closed without merging**
