### PR TITLE
[mod_proxy] use gw_plugin_config_free in mod_proxy_free_config to free gw

### PR DESCRIPTION
**Pull request by ggvl**
Signed-off-by: lvgenggeng <lvgenggeng@uniontech.com>

### CODE REVIEW

**Comment by gstrauss** [comment]
You changed the original title, so it appears that you were looking in this area in the code for a reason.
What problem are you trying to solve with this change?

Since lighttpd mod_proxy inherits and extends `gw_handler_ctx`, `gw_free()` must be called after everything else is handled in `mod_proxy_free_config()`, which is what the code currently does.  Your PR breaks this.  Why?

**Comment by ggvl** [comment]
`cleanup` callback is called by `plugins_free()`. `gw_free()` do the same things with a for loop again. We don't want to loop twice.

**Comment by gstrauss** [comment]
What problem are you trying to solve with this change?  Please be specific.

**Comment by gstrauss** [comment]
You appear to have ignored my first explanation on why your patch is incorrect.

You seem to be trying to "optimize" a for loop that is expected to run on a small number of items, namely the number of scopes containing `proxy.*` configuration directives, and this loop runs at server shutdown or restart.

**Pull request closed without merging**
